/**
 * This class is generated by jOOQ
 */
package com.example.jooq.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actor implements Serializable {

    private static final long serialVersionUID = 2009679047;

    private Integer   id;
    private String    name;
    private Short     height;
    private String    blood;
    private Short     birthplaceId;
    private Date      birthday;
    private Timestamp updateAt;

    public Actor() {}

    public Actor(Actor value) {
        this.id = value.id;
        this.name = value.name;
        this.height = value.height;
        this.blood = value.blood;
        this.birthplaceId = value.birthplaceId;
        this.birthday = value.birthday;
        this.updateAt = value.updateAt;
    }

    public Actor(
        Integer   id,
        String    name,
        Short     height,
        String    blood,
        Short     birthplaceId,
        Date      birthday,
        Timestamp updateAt
    ) {
        this.id = id;
        this.name = name;
        this.height = height;
        this.blood = blood;
        this.birthplaceId = birthplaceId;
        this.birthday = birthday;
        this.updateAt = updateAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Short getHeight() {
        return this.height;
    }

    public void setHeight(Short height) {
        this.height = height;
    }

    public String getBlood() {
        return this.blood;
    }

    public void setBlood(String blood) {
        this.blood = blood;
    }

    public Short getBirthplaceId() {
        return this.birthplaceId;
    }

    public void setBirthplaceId(Short birthplaceId) {
        this.birthplaceId = birthplaceId;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Actor (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(height);
        sb.append(", ").append(blood);
        sb.append(", ").append(birthplaceId);
        sb.append(", ").append(birthday);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }
}
