# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 9000

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
#Database Configuration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.159.130:3306/jooqdb
    username: mysql
    password: Mysql#123
    initialize: false
    continueOnError: true
# JOOQ
jooq:
  sql:
    dialect: MySQL

