/**
 * This class is generated by jOOQ
 */
package com.example.jooq.db;


import com.example.jooq.db.tables.Actor;
import com.example.jooq.db.tables.Prefecture;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooqdb extends SchemaImpl {

    private static final long serialVersionUID = -1878485511;

    /**
     * The reference instance of <code>jooqdb</code>
     */
    public static final Jooqdb JOOQDB = new Jooqdb();

    /**
     * The table <code>jooqdb.actor</code>.
     */
    public final Actor ACTOR = com.example.jooq.db.tables.Actor.ACTOR;

    /**
     * The table <code>jooqdb.prefecture</code>.
     */
    public final Prefecture PREFECTURE = com.example.jooq.db.tables.Prefecture.PREFECTURE;

    /**
     * No further instances allowed
     */
    private Jooqdb() {
        super("jooqdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Actor.ACTOR,
            Prefecture.PREFECTURE);
    }
}
