/**
 * This class is generated by jOOQ
 */
package com.example.jooq.db;


import com.example.jooq.db.tables.Actor;
import com.example.jooq.db.tables.Prefecture;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooqdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqdb.actor</code>.
     */
    public static final Actor ACTOR = com.example.jooq.db.tables.Actor.ACTOR;

    /**
     * The table <code>jooqdb.prefecture</code>.
     */
    public static final Prefecture PREFECTURE = com.example.jooq.db.tables.Prefecture.PREFECTURE;
}
